service: posts-service

provider:
  name: aws
  region: sa-east-1
  stage: prod

useDotenv: true

package:
  patterns:
    - '!**/**'
    - dist/main.js

functions:
  main:
    handler: dist/main.handler
    name: posts-service
    url: true
    runtime: nodejs20.x
    timeout: 15

plugins:
  - serverless-offline
