service: posts-service

provider:
  name: aws
  region: sa-east-1
  stage: prod
  httpApi:
    id: ${env:API_GATEWAY_ID}

useDotenv: true

package:
  patterns:
    - '!**/**'
    - dist/**

functions:
  main:
    handler: dist/main.handler
    name: posts-service
    runtime: nodejs20.x
    timeout: 15
    events:
      - httpApi:
          path: '/posts'
          method: ANY
      - httpApi:
          path: '/posts/{proxy+}'
          method: ANY
    environment:
      MONGO_URI: ${env:MONGO_URI}
      NODE_ENV: prod
      SERVER_MODE: serverless
      AWS_BUCKET_NAME: ${env:AWS_BUCKET_NAME}
      AWS_BUCKET_REGION: ${env:AWS_BUCKET_REGION}

plugins:
  - serverless-offline
